### ISSUE TITLE
MySQL & PostgreSQL?

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/congreso-api#5]
@acrogenesis porqué el Gemfile incluye MySQL & PostgreSQL gems?
https://github.com/CodeandoMexico/congreso-api/blob/master/Gemfile#L7

Veo en el database.yml que usa PostgreSQL and dev & test pero en production usa MySQL.
Deberíamos dejar solamente 1 tipo de DB para tener lo más similar posible en diferentes ENVs

**Comment by acrogenesis** [comment]
cierto, el servidor tiene mysql entonces lo más sencillo es usar mysql tmb en dev ahorita lo arreglo

**Comment by acrogenesis** [comment]
ya quedo en a6d5176
