### ISSUE TITLE
InitiativeParse a rake task

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/congreso-api#6]
Sería más descriptivo que en lugar de ser un modelo de la aplicación, sea un rake task, para que se pueda correr desde terminal y no desde la consola de rails,
facilitaría también montarlo en un cron job a futuro.

Qué opinas @acrogenesis ?

**Comment by acrogenesis** [comment]
eso mismo estaba pensando cuando lo corrí, deja me pongo a hacer eso

**Comment by acrogenesis** [comment]
listo en efd25aa0b7
